export interface IPhone {
  model: string
  variant: string
  storage: string
  color: string
  country: string
  simType: string
  price: number
}

export const iphones: IPhone[] = [
  // iPhone 8
  {
    model: '8',
    variant: '',
    storage: '64GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 150,
  },
  {
    model: '8',
    variant: '',
    storage: '64GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 150,
  },
  {
    model: '8',
    variant: '',
    storage: '64GB',
    color: 'R',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 155,
  },
  {
    model: '8',
    variant: '',
    storage: '64GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 160,
  },
  {
    model: '8',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 200,
  },
  {
    model: '8',
    variant: '',
    storage: '256GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 200,
  },
  {
    model: '8',
    variant: '',
    storage: '256GB',
    color: 'R',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 205,
  },
  {
    model: '8',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 210,
  },
  {
    model: '8',
    variant: 'Plus',
    storage: '64GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 180,
  },
  {
    model: '8',
    variant: 'Plus',
    storage: '64GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 180,
  },
  {
    model: '8',
    variant: 'Plus',
    storage: '64GB',
    color: 'R',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 185,
  },
  {
    model: '8',
    variant: 'Plus',
    storage: '64GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 190,
  },
  {
    model: '8',
    variant: 'Plus',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 230,
  },
  {
    model: '8',
    variant: 'Plus',
    storage: '256GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 230,
  },
  {
    model: '8',
    variant: 'Plus',
    storage: '256GB',
    color: 'R',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 235,
  },
  {
    model: '8',
    variant: 'Plus',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 240,
  },

  // iPhone X
  {
    model: 'X',
    variant: '',
    storage: '64GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 250,
  },
  {
    model: 'X',
    variant: '',
    storage: '64GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 250,
  },
  {
    model: 'X',
    variant: '',
    storage: '64GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 260,
  },
  {
    model: 'X',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 300,
  },
  {
    model: 'X',
    variant: '',
    storage: '256GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 300,
  },
  {
    model: 'X',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 310,
  },

  // iPhone 11
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 350,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 350,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'R',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 355,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'G',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 355,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 360,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 400,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 400,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'R',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 405,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'G',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 405,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 410,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 450,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 450,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'G',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 455,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 460,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 500,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 500,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'G',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 505,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 510,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 500,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 500,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'G',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 505,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 510,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 550,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 550,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'G',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 555,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 560,
  },

  // iPhone 12
  {
    model: '12',
    variant: 'Mini',
    storage: '64GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 400,
  },
  {
    model: '12',
    variant: 'Mini',
    storage: '64GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 400,
  },
  {
    model: '12',
    variant: 'Mini',
    storage: '64GB',
    color: 'R',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 405,
  },
  {
    model: '12',
    variant: 'Mini',
    storage: '64GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 410,
  },
  {
    model: '12',
    variant: 'Mini',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 450,
  },
  {
    model: '12',
    variant: 'Mini',
    storage: '128GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 450,
  },
  {
    model: '12',
    variant: 'Mini',
    storage: '128GB',
    color: 'R',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 455,
  },
  {
    model: '12',
    variant: 'Mini',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 460,
  },
  {
    model: '12',
    variant: '',
    storage: '64GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 450,
  },
  {
    model: '12',
    variant: '',
    storage: '64GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 450,
  },
  {
    model: '12',
    variant: '',
    storage: '64GB',
    color: 'R',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 455,
  },
  {
    model: '12',
    variant: '',
    storage: '64GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 460,
  },
  {
    model: '12',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 500,
  },
  {
    model: '12',
    variant: '',
    storage: '128GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 500,
  },
  {
    model: '12',
    variant: '',
    storage: '128GB',
    color: 'R',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 505,
  },
  {
    model: '12',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 510,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 600,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 600,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 610,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 650,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 650,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 660,
  },
  {
    model: '12',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 700,
  },
  {
    model: '12',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 700,
  },
  {
    model: '12',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 710,
  },
  {
    model: '12',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 750,
  },
  {
    model: '12',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 750,
  },
  {
    model: '12',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 760,
  },

  // iPhone 13
  {
    model: '13',
    variant: 'Mini',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 500,
  },
  {
    model: '13',
    variant: 'Mini',
    storage: '128GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 500,
  },
  {
    model: '13',
    variant: 'Mini',
    storage: '128GB',
    color: 'R',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 505,
  },
  {
    model: '13',
    variant: 'Mini',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 510,
  },
  {
    model: '13',
    variant: 'Mini',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 510,
  },
  {
    model: '13',
    variant: 'Mini',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 550,
  },
  {
    model: '13',
    variant: 'Mini',
    storage: '256GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 550,
  },
  {
    model: '13',
    variant: 'Mini',
    storage: '256GB',
    color: 'R',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 555,
  },
  {
    model: '13',
    variant: 'Mini',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 560,
  },
  {
    model: '13',
    variant: 'Mini',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 560,
  },
  {
    model: '13',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 550,
  },
  {
    model: '13',
    variant: '',
    storage: '128GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 550,
  },
  {
    model: '13',
    variant: '',
    storage: '128GB',
    color: 'R',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 555,
  },
  {
    model: '13',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 560,
  },
  {
    model: '13',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 560,
  },
  {
    model: '13',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 600,
  },
  {
    model: '13',
    variant: '',
    storage: '256GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 600,
  },
  {
    model: '13',
    variant: '',
    storage: '256GB',
    color: 'R',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 605,
  },
  {
    model: '13',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 610,
  },
  {
    model: '13',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 610,
  },
  {
    model: '13',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 700,
  },
  {
    model: '13',
    variant: 'Pro',
    storage: '128GB',
    color: 'Wh',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 700,
  },
  {
    model: '13',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 710,
  },
  {
    model: '13',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 750,
  },
  {
    model: '13',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 750,
  },
  {
    model: '13',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 760,
  },
  {
    model: '13',
    variant: 'Pro',
    storage: '1TB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 900,
  },
  {
    model: '13',
    variant: 'Pro',
    storage: '1TB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 910,
  },
  {
    model: '13',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 800,
  },
  {
    model: '13',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Wh',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 800,
  },
  {
    model: '13',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 810,
  },
  {
    model: '13',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 850,
  },
  {
    model: '13',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Wh',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 850,
  },
  {
    model: '13',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 860,
  },
  {
    model: '13',
    variant: 'Pro Max',
    storage: '1TB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1000,
  },
  {
    model: '13',
    variant: 'Pro Max',
    storage: '1TB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 1010,
  },

  // iPhone 14
  {
    model: '14',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 600,
  },
  {
    model: '14',
    variant: '',
    storage: '128GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 600,
  },
  {
    model: '14',
    variant: '',
    storage: '128GB',
    color: 'R',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 605,
  },
  {
    model: '14',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 610,
  },
  {
    model: '14',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 610,
  },
  {
    model: '14',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 650,
  },
  {
    model: '14',
    variant: '',
    storage: '256GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 650,
  },
  {
    model: '14',
    variant: '',
    storage: '256GB',
    color: 'R',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 655,
  },
  {
    model: '14',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 660,
  },
  {
    model: '14',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 660,
  },
  {
    model: '14',
    variant: 'Plus',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 650,
  },
  {
    model: '14',
    variant: 'Plus',
    storage: '128GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 650,
  },
  {
    model: '14',
    variant: 'Plus',
    storage: '128GB',
    color: 'R',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 655,
  },
  {
    model: '14',
    variant: 'Plus',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 660,
  },
  {
    model: '14',
    variant: 'Plus',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 660,
  },
  {
    model: '14',
    variant: 'Plus',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 700,
  },
  {
    model: '14',
    variant: 'Plus',
    storage: '256GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 700,
  },
  {
    model: '14',
    variant: 'Plus',
    storage: '256GB',
    color: 'R',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 705,
  },
  {
    model: '14',
    variant: 'Plus',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 710,
  },
  {
    model: '14',
    variant: 'Plus',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 710,
  },
  {
    model: '14',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 800,
  },
  {
    model: '14',
    variant: 'Pro',
    storage: '128GB',
    color: 'Wh',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 800,
  },
  {
    model: '14',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 810,
  },
  {
    model: '14',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 850,
  },
  {
    model: '14',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 850,
  },
  {
    model: '14',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 860,
  },
  {
    model: '14',
    variant: 'Pro',
    storage: '1TB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1000,
  },
  {
    model: '14',
    variant: 'Pro',
    storage: '1TB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 1010,
  },
  {
    model: '14',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 900,
  },
  {
    model: '14',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Wh',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 900,
  },
  {
    model: '14',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 910,
  },
  {
    model: '14',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 950,
  },
  {
    model: '14',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Wh',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 950,
  },
  {
    model: '14',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 960,
  },
  {
    model: '14',
    variant: 'Pro Max',
    storage: '1TB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1100,
  },
  {
    model: '14',
    variant: 'Pro Max',
    storage: '1TB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 1110,
  },

  // iPhone 15
  {
    model: '15',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 799,
  },
  {
    model: '15',
    variant: '',
    storage: '128GB',
    color: 'G',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 804,
  },
  {
    model: '15',
    variant: '',
    storage: '128GB',
    color: 'C',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 804,
  },
  {
    model: '15',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 809,
  },
  {
    model: '15',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 809,
  },
  {
    model: '15',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 899,
  },
  {
    model: '15',
    variant: '',
    storage: '256GB',
    color: 'G',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 904,
  },
  {
    model: '15',
    variant: '',
    storage: '256GB',
    color: 'C',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 904,
  },
  {
    model: '15',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 909,
  },
  {
    model: '15',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 909,
  },
  {
    model: '15',
    variant: 'Plus',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 899,
  },
  {
    model: '15',
    variant: 'Plus',
    storage: '128GB',
    color: 'G',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 904,
  },
  {
    model: '15',
    variant: 'Plus',
    storage: '128GB',
    color: 'C',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 904,
  },
  {
    model: '15',
    variant: 'Plus',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 909,
  },
  {
    model: '15',
    variant: 'Plus',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 909,
  },
  {
    model: '15',
    variant: 'Plus',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 999,
  },
  {
    model: '15',
    variant: 'Plus',
    storage: '256GB',
    color: 'G',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 1004,
  },
  {
    model: '15',
    variant: 'Plus',
    storage: '256GB',
    color: 'C',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 1004,
  },
  {
    model: '15',
    variant: 'Plus',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 1009,
  },
  {
    model: '15',
    variant: 'Plus',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 1009,
  },
  {
    model: '15',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 999,
  },
  {
    model: '15',
    variant: 'Pro',
    storage: '128GB',
    color: 'Wh',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 999,
  },
  {
    model: '15',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 1009,
  },
  {
    model: '15',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1099,
  },
  {
    model: '15',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1099,
  },
  {
    model: '15',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 1109,
  },
  {
    model: '15',
    variant: 'Pro',
    storage: '1TB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1299,
  },
  {
    model: '15',
    variant: 'Pro',
    storage: '1TB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 1309,
  },
  {
    model: '15',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1299,
  },
  {
    model: '15',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Wh',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1299,
  },
  {
    model: '15',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 1309,
  },
  {
    model: '15',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1499,
  },
  {
    model: '15',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Wh',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1499,
  },
  {
    model: '15',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 1509,
  },
  {
    model: '15',
    variant: 'Pro Max',
    storage: '1TB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1699,
  },
  {
    model: '15',
    variant: 'Pro Max',
    storage: '1TB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 1709,
  },

  // iPhone 16
  {
    model: '16',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 899,
  },
  {
    model: '16',
    variant: '',
    storage: '128GB',
    color: 'G',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 904,
  },
  {
    model: '16',
    variant: '',
    storage: '128GB',
    color: 'C',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 904,
  },
  {
    model: '16',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 909,
  },
  {
    model: '16',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 909,
  },
  {
    model: '16',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 999,
  },
  {
    model: '16',
    variant: '',
    storage: '256GB',
    color: 'G',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 1004,
  },
  {
    model: '16',
    variant: '',
    storage: '256GB',
    color: 'C',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 1004,
  },
  {
    model: '16',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 1009,
  },
  {
    model: '16',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 1009,
  },
  {
    model: '16',
    variant: 'Plus',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 999,
  },
  {
    model: '16',
    variant: 'Plus',
    storage: '128GB',
    color: 'G',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 1004,
  },
  {
    model: '16',
    variant: 'Plus',
    storage: '128GB',
    color: 'C',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 1004,
  },
  {
    model: '16',
    variant: 'Plus',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 1009,
  },
  {
    model: '16',
    variant: 'Plus',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 1009,
  },
  {
    model: '16',
    variant: 'Plus',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 1099,
  },
  {
    model: '16',
    variant: 'Plus',
    storage: '256GB',
    color: 'G',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 1104,
  },
  {
    model: '16',
    variant: 'Plus',
    storage: '256GB',
    color: 'C',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 1104,
  },
  {
    model: '16',
    variant: 'Plus',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '2 SIM',
    price: 1109,
  },
  {
    model: '16',
    variant: 'Plus',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 1109,
  },
  {
    model: '16',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1199,
  },
  {
    model: '16',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1199,
  },
  {
    model: '16',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 1209,
  },
  {
    model: '16',
    variant: 'Pro',
    storage: '512GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1399,
  },
  {
    model: '16',
    variant: 'Pro',
    storage: '512GB',
    color: 'Wh',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1399,
  },
  {
    model: '16',
    variant: 'Pro',
    storage: '512GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 1409,
  },
  {
    model: '16',
    variant: 'Pro',
    storage: '1TB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1599,
  },
  {
    model: '16',
    variant: 'Pro',
    storage: '1TB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 1609,
  },
  {
    model: '16',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1499,
  },
  {
    model: '16',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Wh',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1499,
  },
  {
    model: '16',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 1509,
  },
  {
    model: '16',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1699,
  },
  {
    model: '16',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Wh',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1699,
  },
  {
    model: '16',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 1709,
  },
  {
    model: '16',
    variant: 'Pro Max',
    storage: '1TB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: '1 SIM',
    price: 1899,
  },
  {
    model: '16',
    variant: 'Pro Max',
    storage: '1TB',
    color: 'Bl',
    country: 'India 🇮🇳',
    simType: 'eSIM',
    price: 1909,
  },
  {
    model: '16',
    variant: 'e',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 699,
  },
  {
    model: '16',
    variant: 'e',
    storage: '128GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 699,
  },
  {
    model: '16',
    variant: 'e',
    storage: '128GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 704,
  },
  {
    model: '16',
    variant: 'e',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 799,
  },
  {
    model: '16',
    variant: 'e',
    storage: '256GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 799,
  },
  {
    model: '16',
    variant: 'e',
    storage: '256GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 804,
  },
  {
    model: '16',
    variant: 'e',
    storage: '512GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 899,
  },
  {
    model: '16',
    variant: 'e',
    storage: '512GB',
    color: 'Wh',
    country: 'China 🇨🇳',
    simType: '1 SIM',
    price: 899,
  },
  {
    model: '16',
    variant: 'e',
    storage: '512GB',
    color: 'Bl',
    country: 'China 🇨🇳',
    simType: 'eSIM',
    price: 904,
  },
]
