export interface AppleModel {
  model: string
  variant: string
  storage: string
  color: string
  country: string
  simType: string
  basePrice: number
}

export const appleModels: AppleModel[] = [
  {
    model: 'X',
    variant: 'R',
    storage: '64GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 13500,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '64GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 13500,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '64GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 13950,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '64GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 13950,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '256GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '256GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 18000,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '256GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 18450,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '256GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 18450,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '64GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 13500,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '64GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 13500,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '64GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 13950,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '64GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 13950,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '256GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '256GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 18000,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '256GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 18450,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '256GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 18450,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '64GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 13500,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '64GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 13500,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '64GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 13950,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '64GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 13950,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '256GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '256GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 18000,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '256GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 18450,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '256GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 18450,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '64GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 13500,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '64GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 13950,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '256GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: 'X',
    variant: 'R',
    storage: '256GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 18450,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '64GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 15300,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '64GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 15300,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '64GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 15750,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '64GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 15750,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '256GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 19800,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '256GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 19800,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '256GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 20250,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '256GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 20250,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '64GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 15300,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '64GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 15300,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '64GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 15750,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '64GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 15750,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '256GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 19800,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '256GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 19800,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '256GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 20250,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '256GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 20250,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '64GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 15300,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '64GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 15300,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '64GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 15750,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '64GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 15750,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '256GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 19800,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '256GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 19800,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '256GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 20250,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '256GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 20250,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '64GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 15300,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '64GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 15750,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '256GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 19800,
  },
  {
    model: 'X',
    variant: 'S',
    storage: '256GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 20250,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '64GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '64GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 18000,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '64GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 18450,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '64GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 18450,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '256GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 22500,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '256GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 22500,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '256GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 22950,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '256GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 22950,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '64GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '64GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 18000,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '64GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 18450,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '64GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 18450,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '256GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 22500,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '256GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 22500,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '256GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 22950,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '256GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 22950,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '64GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '64GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 18000,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '64GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 18450,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '64GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 18450,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '256GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 22500,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '256GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 22500,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '256GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 22950,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '256GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 22950,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '64GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '64GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 18450,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '256GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 22500,
  },
  {
    model: 'X',
    variant: 'S Max',
    storage: '256GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 22950,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '64GB',
    color: 'G',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 16000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '128GB',
    color: 'G',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 14000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '256GB',
    color: 'G',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 22000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro',
    storage: '512GB',
    color: 'G',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 27000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '64GB',
    color: 'G',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 18000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '128GB',
    color: 'G',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 21000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '256GB',
    color: 'G',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: 'Pro Max',
    storage: '512GB',
    color: 'G',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'R',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'R',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'R',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'R',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'R',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'G',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '64GB',
    color: 'R',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'R',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'R',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'R',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'R',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'R',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'G',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '128GB',
    color: 'R',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 24000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'R',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'R',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'R',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'R',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'R',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'G',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '256GB',
    color: 'R',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 20000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'R',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'R',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'R',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'R',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'R',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'G',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '11',
    variant: '',
    storage: '512GB',
    color: 'R',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '128GB',
    color: 'G',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 28000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '256GB',
    color: 'G',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 30000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'Bl',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'Wh',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '1 SIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'G',
    country: 'Китай 🇨🇳',
    simType: '2 SIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'Bl',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'Wh',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: '1 SIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'G',
    country: 'США 🇺🇸',
    simType: 'eSIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'Bl',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'Wh',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: '1 SIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'G',
    country: 'Европа 🇪🇺',
    simType: 'eSIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'Bl',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'Wh',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 32000,
  },
  {
    model: '12',
    variant: 'Pro',
    storage: '512GB',
    color: 'G',
    country: 'ОАЭ 🇦🇪',
    simType: '1 SIM',
    basePrice: 32000,
  },
]
